
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tgf
 */
public class BoardingPass extends javax.swing.JInternalFrame {

    /**
     * Creates new form BoardingPass
     */
    public BoardingPass() {
        initComponents();
        this.setBorder(null);
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        bi.setSouthPane(null);
        bi.setEastPane(null);
        bi.setWestPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        departtime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flightid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        source = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        depart = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        class1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tino = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(36, 29, 62));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 121, 44));
        jLabel1.setText("DEPARTURE");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 79, 153, -1));

        departtime.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        departtime.setForeground(new java.awt.Color(244, 121, 44));
        departtime.setText("TIME");
        departtime.setToolTipText("");
        getContentPane().add(departtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 105, 153, -1));

        jLabel3.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(244, 121, 44));
        jLabel3.setText("FLIGHT NO.");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 178, 153, -1));

        flightid.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        flightid.setForeground(new java.awt.Color(244, 121, 44));
        flightid.setText("FLXXX");
        flightid.setToolTipText("");
        getContentPane().add(flightid, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 209, 153, -1));

        jLabel5.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 121, 44));
        jLabel5.setText("NAME OF PASSENGER");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 79, -1, -1));

        name.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(244, 121, 44));
        name.setText("XYZ");
        name.setToolTipText("");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 105, 153, -1));

        jLabel7.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 121, 44));
        jLabel7.setText("GATE");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 178, 153, -1));

        gate.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        gate.setForeground(new java.awt.Color(244, 121, 44));
        gate.setText("X");
        gate.setToolTipText("");
        getContentPane().add(gate, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 209, 153, -1));

        jLabel9.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(244, 121, 44));
        jLabel9.setText("FROM");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 79, 153, -1));

        source.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        source.setForeground(new java.awt.Color(244, 121, 44));
        source.setText("PLACE");
        source.setToolTipText("");
        getContentPane().add(source, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 105, 153, -1));

        jLabel11.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(244, 121, 44));
        jLabel11.setText("TO");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 178, 153, -1));

        depart.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        depart.setForeground(new java.awt.Color(244, 121, 44));
        depart.setText("PLACE");
        depart.setToolTipText("");
        getContentPane().add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 209, 153, -1));

        jLabel13.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(244, 121, 44));
        jLabel13.setText("CLASS");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 79, 153, -1));

        class1.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        class1.setForeground(new java.awt.Color(244, 121, 44));
        class1.setText("ECO/BUS");
        class1.setToolTipText("");
        getContentPane().add(class1, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 105, 153, -1));

        jLabel15.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(244, 121, 44));
        jLabel15.setText("SEAT");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 178, 153, -1));

        seat.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        seat.setForeground(new java.awt.Color(244, 121, 44));
        seat.setText("XX/X");
        seat.setToolTipText("");
        getContentPane().add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 209, 153, -1));

        jLabel17.setFont(new java.awt.Font("Source Code Pro", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(244, 121, 44));
        jLabel17.setText("TICKET NO:");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 26, -1, -1));

        tino.setBackground(new java.awt.Color(36, 29, 62));
        tino.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
        tino.setForeground(new java.awt.Color(244, 121, 44));
        tino.setBorder(null);
        tino.setCaretColor(new java.awt.Color(244, 121, 44));
        getContentPane().add(tino, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 23, 57, -1));

        jSeparator1.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator1.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 57, 1));

        jToggleButton1.setBackground(new java.awt.Color(36, 29, 62));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(36, 29, 62));
        jToggleButton1.setText("  ");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 121, 44), 2));
        jToggleButton1.setFocusable(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 25, 20, 20));

        jSeparator2.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator2.setForeground(new java.awt.Color(244, 121, 44));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 47, 57, 14));

        jSeparator3.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator3.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 57, 3));

        jSeparator4.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator4.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator4.setOpaque(true);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 57, 5));

        jSeparator5.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator5.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 3));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 57, 10));

        jSeparator6.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator6.setForeground(new java.awt.Color(244, 121, 44));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 57, 6));

        jSeparator7.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator7.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator7.setOpaque(true);
        jSeparator7.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 57, 3));

        jSeparator8.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator8.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator8.setOpaque(true);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 57, 5));

        jSeparator9.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator9.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator9.setPreferredSize(new java.awt.Dimension(0, 3));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 57, 10));

        jSeparator10.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator10.setForeground(new java.awt.Color(244, 121, 44));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 57, 6));

        jSeparator11.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator11.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator11.setOpaque(true);
        jSeparator11.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 57, 3));

        jSeparator12.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator12.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator12.setOpaque(true);
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 57, 1));

        jSeparator13.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator13.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator13.setPreferredSize(new java.awt.Dimension(0, 3));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 57, 10));

        jSeparator14.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator14.setForeground(new java.awt.Color(244, 121, 44));
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 57, 6));

        jSeparator15.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator15.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator15.setOpaque(true);
        jSeparator15.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 57, 3));

        jSeparator16.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator16.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator16.setOpaque(true);
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 57, 5));

        jSeparator17.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator17.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator17.setPreferredSize(new java.awt.Dimension(0, 3));
        getContentPane().add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 57, 10));

        jSeparator18.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator18.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator18.setOpaque(true);
        getContentPane().add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 57, 1));

        jSeparator19.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator19.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator19.setPreferredSize(new java.awt.Dimension(0, 3));
        getContentPane().add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 57, 10));

        jSeparator20.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator20.setForeground(new java.awt.Color(244, 121, 44));
        getContentPane().add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 57, 6));

        jSeparator21.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator21.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator21.setOpaque(true);
        jSeparator21.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 57, 3));

        jSeparator22.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator22.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator22.setOpaque(true);
        getContentPane().add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 57, 5));

        jSeparator23.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator23.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator23.setPreferredSize(new java.awt.Dimension(0, 3));
        getContentPane().add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 57, 10));

        jSeparator24.setBackground(new java.awt.Color(244, 121, 44));
        jSeparator24.setForeground(new java.awt.Color(244, 121, 44));
        jSeparator24.setOpaque(true);
        jSeparator24.setPreferredSize(new java.awt.Dimension(0, 1));
        getContentPane().add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 57, 3));

        setBounds(50, 140, 1272, 312);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String id = tino.getText();
        try {
            conn cl = new conn();
            PreparedStatement pst = cl.con.prepareStatement("select * from ticket where id = ?");
            pst.setString(1,id);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()== false){
                JOptionPane.showMessageDialog(this, "Record not Found");
            }
            else {
                String firstname = rs.getString("name");
                String flightno = rs.getString("flightid");
                String dtime = rs.getString("departtime");
                String source1 = rs.getString("source");
                String depart1 = rs.getString("depart");
                String clas = rs.getString("class");
                
                name.setText(firstname.trim().toUpperCase());
                flightid.setText(flightno.trim().toUpperCase());
                departtime.setText(dtime.trim());
                source.setText(source1.trim().toUpperCase());
                depart.setText(depart1.trim().toUpperCase());
                class1.setText(clas.trim().toUpperCase());                
                Random rand = new Random(); 
                int i = rand.nextInt(30);
                 seat.setText(String.format("%d", i)+ "A");
                int g = rand.nextInt(5);
                 gate.setText("H" + String.format("%d", g));
                
            }
            
        } 
        catch (SQLException e){
            System.out.println("SQL Error 3");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel class1;
    private javax.swing.JLabel depart;
    private javax.swing.JLabel departtime;
    private javax.swing.JLabel flightid;
    private javax.swing.JLabel gate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel seat;
    private javax.swing.JLabel source;
    private javax.swing.JTextField tino;
    // End of variables declaration//GEN-END:variables
}
