import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class searchCustomer extends javax.swing.JInternalFrame {

    private PreparedStatement pst;

    

    /**
     * Creates new form addCustomer
     */
    public searchCustomer() {
        initComponents();
        this.setBorder(null);
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        bi.setSouthPane(null);
        bi.setEastPane(null);
        bi.setWestPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        txtcustid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpassport = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdob = new com.toedter.calendar.JDateChooser();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(36, 29, 62));
        setPreferredSize(new java.awt.Dimension(1025, 650));

        jToggleButton1.setBackground(new java.awt.Color(36, 29, 62));
        jToggleButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(241, 85, 116));
        jToggleButton1.setText("Cancel");
        jToggleButton1.setToolTipText("");
        jToggleButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 85, 116), 2, true));
        jToggleButton1.setOpaque(true);
        jToggleButton1.setRequestFocusEnabled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(36, 29, 62));
        jToggleButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(241, 85, 116));
        jToggleButton2.setText("Update");
        jToggleButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 85, 116), 2, true));
        jToggleButton2.setOpaque(true);
        jToggleButton2.setRequestFocusEnabled(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        txtcustid.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtcustid.setForeground(new java.awt.Color(232, 168, 240));
        txtcustid.setBorder(null);
        txtcustid.setCaretColor(new java.awt.Color(182, 83, 125));
        txtcustid.setMargin(new java.awt.Insets(2, 4, 2, 2));
        txtcustid.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(241, 85, 116));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(241, 85, 116));
        jButton1.setText("Find");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 85, 116), 2, true));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(241, 85, 116));
        jLabel7.setText("Customer ID:");

        jSeparator3.setBackground(new java.awt.Color(238, 116, 162));
        jSeparator3.setForeground(new java.awt.Color(238, 116, 162));

        jSeparator4.setBackground(new java.awt.Color(238, 116, 162));
        jSeparator4.setForeground(new java.awt.Color(238, 116, 162));

        jLabel1.setBackground(new java.awt.Color(241, 85, 116));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 85, 116));
        jLabel1.setText("FirstName");

        txtfirstname.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtfirstname.setForeground(new java.awt.Color(232, 168, 240));
        txtfirstname.setBorder(null);
        txtfirstname.setCaretColor(new java.awt.Color(182, 83, 125));
        txtfirstname.setMargin(new java.awt.Insets(2, 4, 2, 2));
        txtfirstname.setOpaque(false);
        txtfirstname.setPreferredSize(new java.awt.Dimension(67, 27));

        jSeparator1.setBackground(new java.awt.Color(238, 116, 162));
        jSeparator1.setForeground(new java.awt.Color(238, 116, 162));

        jLabel2.setBackground(new java.awt.Color(241, 85, 116));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 85, 116));
        jLabel2.setText("Last Name");

        txtlastname.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(232, 168, 240));
        txtlastname.setBorder(null);
        txtlastname.setCaretColor(new java.awt.Color(182, 83, 125));
        txtlastname.setMargin(new java.awt.Insets(2, 4, 2, 2));
        txtlastname.setOpaque(false);
        txtlastname.setPreferredSize(new java.awt.Dimension(67, 27));

        jSeparator2.setBackground(new java.awt.Color(238, 116, 162));
        jSeparator2.setForeground(new java.awt.Color(238, 116, 162));

        jLabel3.setBackground(new java.awt.Color(241, 85, 116));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 85, 116));
        jLabel3.setText("Aadhar No.");

        txtnic.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtnic.setForeground(new java.awt.Color(232, 168, 240));
        txtnic.setBorder(null);
        txtnic.setCaretColor(new java.awt.Color(182, 83, 125));
        txtnic.setMargin(new java.awt.Insets(2, 4, 2, 2));
        txtnic.setOpaque(false);
        txtnic.setPreferredSize(new java.awt.Dimension(67, 27));

        jLabel4.setBackground(new java.awt.Color(241, 85, 116));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 85, 116));
        jLabel4.setText("Passport ID");

        txtpassport.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtpassport.setForeground(new java.awt.Color(232, 168, 240));
        txtpassport.setBorder(null);
        txtpassport.setCaretColor(new java.awt.Color(182, 83, 125));
        txtpassport.setMargin(new java.awt.Insets(2, 4, 2, 2));
        txtpassport.setOpaque(false);
        txtpassport.setPreferredSize(new java.awt.Dimension(67, 27));

        txtcontact.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(232, 168, 240));
        txtcontact.setBorder(null);
        txtcontact.setCaretColor(new java.awt.Color(182, 83, 125));
        txtcontact.setMargin(new java.awt.Insets(2, 4, 2, 2));
        txtcontact.setOpaque(false);
        txtcontact.setPreferredSize(new java.awt.Dimension(60, 26));
        txtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(241, 85, 116));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(241, 85, 116));
        jLabel10.setText("Contact");

        jLabel9.setBackground(new java.awt.Color(241, 85, 116));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(241, 85, 116));
        jLabel9.setText("Gender");

        jSeparator5.setBackground(new java.awt.Color(238, 116, 162));
        jSeparator5.setForeground(new java.awt.Color(238, 116, 162));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtaddress.setBackground(new java.awt.Color(36, 29, 62));
        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(238, 116, 162));
        txtaddress.setLineWrap(true);
        txtaddress.setRows(5);
        txtaddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 116, 162), 2, true));
        txtaddress.setCaretColor(new java.awt.Color(182, 83, 125));
        txtaddress.setMargin(new java.awt.Insets(2, 4, 2, 2));
        jScrollPane1.setViewportView(txtaddress);

        jLabel5.setBackground(new java.awt.Color(241, 85, 116));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 85, 116));
        jLabel5.setText("Address");

        jLabel8.setBackground(new java.awt.Color(241, 85, 116));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(241, 85, 116));
        jLabel8.setText("Date Of Birth");

        txtdob.setBackground(new java.awt.Color(36, 29, 62));
        txtdob.setForeground(new java.awt.Color(36, 29, 62));
        txtdob.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtdob.setOpaque(false);

        r1.setBackground(new java.awt.Color(36, 29, 62));
        r1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        r1.setForeground(new java.awt.Color(204, 159, 153));
        r1.setText("Male");
        r1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setBackground(new java.awt.Color(36, 29, 62));
        r2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        r2.setForeground(new java.awt.Color(204, 159, 153));
        r2.setText("Female");

        jSeparator6.setBackground(new java.awt.Color(238, 116, 162));
        jSeparator6.setForeground(new java.awt.Color(238, 116, 162));

        jSeparator7.setBackground(new java.awt.Color(238, 116, 162));
        jSeparator7.setForeground(new java.awt.Color(238, 116, 162));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4)
                                .addComponent(jSeparator3)
                                .addComponent(txtpassport, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(r2))
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(txtdob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcontact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7)
                            .addComponent(txtcustid, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                    .addComponent(r1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(r2))))
                        .addGap(8, 8, 8)
                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtpassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setBounds(160, 12, 1025, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        String id = txtcustid.getText();
        String firstname = txtfirstname.getText();
        String lastname = txtlastname.getText();
        String nic = txtnic.getText();
        String passport = txtpassport.getText();
        String address = txtaddress.getText();
        
        DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
        String date = da.format(txtdob.getDate());
        String gender;
        if (r1.isSelected())
            gender = "male";
        else
            gender = "female";
        String contact = txtcontact.getText();
        
        try {
            conn cl = new conn();
            pst = cl.con.prepareStatement("update customer set firstname = ?, lastname = ?, nic = ?, passport = ?, address = ?, dob = ?, gender = ?, contact = ? where id = ?   ");
            
//            pst.setString(1, id);
            pst.setString(1, firstname);
            pst.setString(2, lastname);
            pst.setString(3, nic);
            pst.setString(4, passport);
            pst.setString(5, address);
            pst.setString(6, date);
            pst.setString(7, gender);
            pst.setString(8, contact);
            pst.setString(9, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registration Updated!");
            this.hide();
            
            
        } catch(SQLException e){
            System.out.println("SQL Error2");
        }
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = txtcustid.getText();
        try {
            conn cl = new conn();
            pst = cl.con.prepareStatement("select * from customer where id = ?");
            pst.setString(1,id);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()== false){
                JOptionPane.showMessageDialog(this, "Record not Found");
            }
            else {
                String firstname = rs.getString("firstname");
                String lastname = rs.getString("lastname");
                String nic = rs.getString("nic");
                String passport = rs.getString("passport");
                String address = rs.getString("address");
                String dob = rs.getString("dob");
                Date date1 = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(dob);
                String gender = rs.getString("gender");
                if (gender.equals("female")){
                    r1.setSelected(false);
                    r2.setSelected(true);
                }
                else{
                    r2.setSelected(false);
                    r1.setSelected(true);
                }
                String contact = rs.getString("contact");
                
                txtfirstname.setText(firstname.trim());
                txtlastname.setText(lastname.trim());
                txtnic.setText(nic.trim());
                txtpassport.setText(passport.trim());
                txtaddress.setText(address.trim());
                txtdob.setDate(date1);
                txtcontact.setText(contact.trim());
                
                
                
                
            }
            
        } 
        catch (SQLException e){
            System.out.println("SQL Error 3");
        } catch (ParseException ex) {
            Logger.getLogger(searchCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void txtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtcustid;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpassport;
    // End of variables declaration//GEN-END:variables
}
